### ISSUE TITLE
twilio-go Error

### ISSUE THREAD

**Issue by b3rew** [cheikhshift/megalith#1]
I get this error when i try to `go get github.com/cheikhshift/megalith`

```
$ go get github.com/cheikhshift/megalith
# github.com/saintpete/twilio-go
../go/src/github.com/saintpete/twilio-go/http.go:110:13: unknown field 'StatusCode' in struct literal of type rest.Error
../go/src/github.com/saintpete/twilio-go/http.go:247:15: rerr.StatusCode undefined (type *rest.Error has no field or method StatusCode)

```

please help

**Comment by cheikhshift** [comment]
Which version of go are you using, and do you have the twilio library already?

**Comment by b3rew** [comment]
go version `1.10.3 linux/amd64`
no i didn't have it already
but when i changed `"github.com/saintpete/twilio-go"` to another fork `"github.com/kevinburke/twilio-go"` it workes check it out [repo link](https://github.com/b3rew/megalith)

**Comment by cheikhshift** [comment]
Can we close this? I've tried to recreate this without success.
